CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_SLEEP=n

# EC11 로터리 엔코더 하드웨어 드라이버 강제 탑재
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 무선 BLE 출력 증폭 (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
