# Split 중앙 수신 노드 (Central Dongle)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 절전(Deep Sleep) 비활성화
CONFIG_ZMK_SLEEP=n

# 엔코더 신호 수신 지원
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# 블루투스 송출 출력 증폭 (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
