CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=n

# 센서 서브시스템 및 수신 활성화
CONFIG_SENSOR=y
CONFIG_ZMK_KEYMAP_SENSORS=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
